### ISSUE TITLE
Feature: Show Workshop Maps

### ISSUE THREAD

**Issue by KillerRoi** [mohitkyadav/source-server-manager#46]
Add the ability to show workshop maps that are in the server, and also to change maps into them. Add custom fields commands in the console.

**Comment by mohitkyadav** [comment]
@KillerRoi what do you mean by custom fields command?

**Comment by KillerRoi** [comment]
@mohitkyadav 
![Screenshot_20210801-081507](https://user-images.githubusercontent.com/54289708/127757427-8cbf98fb-9917-4db7-9e08-ce966101c7e5.png)
This is what I'm talking about, everytime the app is being opened it runs these commands which are put in the custom commands field. At every refresh it does that again and again.

**Comment by mohitkyadav** [comment]
you can set custom commands, but to run them you'll have to click on them.
![image](https://user-images.githubusercontent.com/25580776/127757551-fbfc952c-775f-45e6-9a3a-2c0008797434.png)
